from kagni.constants import Response

__all__ = ["test_sequence"]

test_sequence = [
    # ZADD basics
    {
        "name": "Check ZADD return value for new members",
        "command": "ZADD",
        "args": [b"k", b"1", b"a", b"2", b"b"],
        "returns": 2,
    },
    {
        "name": "Check ZADD return value for existing members",
        "command": "ZADD",
        "args": [b"k", b"3", b"a", b"4", b"c"],
        "returns": 1,
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a"], "returns": 1}],
    },
    {
        "name": "Check ZADD NX does not update existing members",
        "command": "ZADD",
        "args": [b"k", b"NX", b"9", b"a", b"5", b"d"],
        "returns": 1,
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a"], "returns": 1}],
        "expects": lambda cs: cs.ZSCORE(b"k", b"a") == b"$1\r\n1\r\n"
        and cs.ZSCORE(b"k", b"d") == b"$1\r\n5\r\n",
    },
    {
        "name": "Check ZADD XX only updates existing members",
        "command": "ZADD",
        "args": [b"k", b"XX", b"9", b"a", b"5", b"d"],
        "returns": 0,
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a"], "returns": 1}],
        "expects": lambda cs: cs.ZSCORE(b"k", b"a") == b"$1\r\n9\r\n"
        and cs.ZCARD(b"k") == b":1\r\n",
    },
    {
        "name": "Check ZADD XX on a missing key creates nothing",
        "command": "ZADD",
        "args": [b"nokey", b"XX", b"1", b"a"],
        "returns": 0,
        "expects": lambda cs: cs.EXISTS(b"nokey") == b":0\r\n",
    },
    {
        "name": "Check ZADD CH counts changed members",
        "command": "ZADD",
        "args": [b"k", b"CH", b"2", b"a", b"7", b"b"],
        "returns": 2,
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a"], "returns": 1}],
    },
    {
        "name": "Check ZADD INCR returns the new score",
        "command": "ZADD",
        "args": [b"k", b"INCR", b"2.5", b"a"],
        "returns": lambda rv, cs: rv == b"3.5",
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a"], "returns": 1}],
    },
    {
        "name": "Check ZADD GT blocks smaller scores but allows new members",
        "command": "ZADD",
        "args": [b"k", b"GT", b"0.5", b"a", b"5", b"new"],
        "returns": 1,
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a"], "returns": 1}],
        "expects": lambda cs: cs.ZSCORE(b"k", b"a") == b"$1\r\n1\r\n"
        and cs.ZSCORE(b"k", b"new") == b"$1\r\n5\r\n",
    },
    # cardinality and scores
    {
        "name": "Check ZCARD on a populated key",
        "command": "ZCARD",
        "args": [b"k"],
        "returns": 3,
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a", b"2", b"b", b"3", b"c"], "returns": 3}],
    },
    {
        "name": "Check ZCARD on a missing key",
        "command": "ZCARD",
        "args": [b"nokey"],
        "returns": 0,
    },
    {
        "name": "Check ZSCORE of a member",
        "command": "ZSCORE",
        "args": [b"k", b"b"],
        "returns": b"2",
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a", b"2", b"b"], "returns": 2}],
    },
    {
        "name": "Check ZSCORE of a missing member",
        "command": "ZSCORE",
        "args": [b"k", b"nope"],
        "returns": Response.NIL,
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a"], "returns": 1}],
    },
    {
        "name": "Check ZSCORE formats scores like redis",
        "command": "ZSCORE",
        "args": [b"k", b"x"],
        "returns": b"10.5",
        "depends": [{"command": "ZADD", "args": [b"k", b"10.5", b"x"], "returns": 1}],
    },
    {
        "name": "Check ZMSCORE replies one slot per member",
        "command": "ZMSCORE",
        "args": [b"k", b"a", b"nope", b"b"],
        "returns": [b"1", Response.NIL, b"2"],
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a", b"2", b"b"], "returns": 2}],
    },
    {
        "name": "Check ZINCRBY creates the member when missing",
        "command": "ZINCRBY",
        "args": [b"nokey", b"1.5", b"m"],
        "returns": b"1.5",
    },
    # ranks
    {
        "name": "Check ZRANK of a member",
        "command": "ZRANK",
        "args": [b"k", b"b"],
        "returns": 1,
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a", b"2", b"b", b"3", b"c"], "returns": 3}],
    },
    {
        "name": "Check ZRANK of a missing member",
        "command": "ZRANK",
        "args": [b"k", b"nope"],
        "returns": Response.NIL,
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a"], "returns": 1}],
    },
    {
        "name": "Check ZRANK WITHSCORE replies rank and score",
        "command": "ZRANK",
        "args": [b"k", b"b", b"WITHSCORE"],
        "returns": [1, b"2"],
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a", b"2", b"b", b"3", b"c"], "returns": 3}],
    },
    {
        "name": "Check ZREVRANK counts from the highest score",
        "command": "ZREVRANK",
        "args": [b"k", b"a"],
        "returns": 2,
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a", b"2", b"b", b"3", b"c"], "returns": 3}],
    },
    # ranges
    {
        "name": "Check ZRANGE over the whole set",
        "command": "ZRANGE",
        "args": [b"k", b"0", b"-1"],
        "returns": [b"a", b"b", b"c"],
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a", b"2", b"b", b"3", b"c"], "returns": 3}],
    },
    {
        "name": "Check ZRANGE WITHSCORES interleaves scores",
        "command": "ZRANGE",
        "args": [b"k", b"0", b"-1", b"WITHSCORES"],
        "returns": [b"a", b"1", b"b", b"2", b"c", b"3"],
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a", b"2", b"b", b"3", b"c"], "returns": 3}],
    },
    {
        "name": "Check ZRANGE with negative indexes",
        "command": "ZRANGE",
        "args": [b"k", b"-2", b"-1"],
        "returns": [b"b", b"c"],
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a", b"2", b"b", b"3", b"c"], "returns": 3}],
    },
    {
        "name": "Check ZRANGE REV returns descending",
        "command": "ZRANGE",
        "args": [b"k", b"0", b"-1", b"REV"],
        "returns": [b"c", b"b", b"a"],
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a", b"2", b"b", b"3", b"c"], "returns": 3}],
    },
    {
        "name": "Check ZRANGE BYSCORE with exclusive bounds",
        "command": "ZRANGE",
        "args": [b"k", b"(1", b"+inf", b"BYSCORE"],
        "returns": [b"b", b"c"],
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a", b"2", b"b", b"3", b"c"], "returns": 3}],
    },
    {
        "name": "Check ZRANGE BYSCORE REV takes max first",
        "command": "ZRANGE",
        "args": [b"k", b"3", b"1", b"BYSCORE", b"REV"],
        "returns": [b"c", b"b", b"a"],
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a", b"2", b"b", b"3", b"c"], "returns": 3}],
    },
    {
        "name": "Check ZRANGE BYSCORE with LIMIT",
        "command": "ZRANGE",
        "args": [b"k", b"-inf", b"+inf", b"BYSCORE", b"LIMIT", b"1", b"1"],
        "returns": [b"b"],
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a", b"2", b"b", b"3", b"c"], "returns": 3}],
    },
    {
        "name": "Check ZRANGE on a missing key",
        "command": "ZRANGE",
        "args": [b"nokey", b"0", b"-1"],
        "returns": [],
    },
    # score ties break on member bytes
    {
        "name": "Check equal scores order by member bytes",
        "command": "ZRANGE",
        "args": [b"k", b"0", b"-1"],
        "returns": [b"a", b"b", b"c"],
        "depends": [
            {"command": "ZADD", "args": [b"k", b"0", b"c", b"0", b"a", b"0", b"b"], "returns": 3}
        ],
    },
    # counts
    {
        "name": "Check ZCOUNT within a score window",
        "command": "ZCOUNT",
        "args": [b"k", b"1", b"2"],
        "returns": 2,
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a", b"2", b"b", b"3", b"c"], "returns": 3}],
    },
    {
        "name": "Check ZCOUNT with exclusive bounds",
        "command": "ZCOUNT",
        "args": [b"k", b"(1", b"+inf"],
        "returns": 2,
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a", b"2", b"b", b"3", b"c"], "returns": 3}],
    },
    # removals and the empty-key invariant
    {
        "name": "Check ZREM removes members",
        "command": "ZREM",
        "args": [b"k", b"a", b"nope"],
        "returns": 1,
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a", b"2", b"b"], "returns": 2}],
    },
    {
        "name": "Check ZREM of the last member deletes the key",
        "command": "ZREM",
        "args": [b"k", b"a"],
        "returns": 1,
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a"], "returns": 1}],
        "expects": lambda cs: cs.EXISTS(b"k") == b":0\r\n",
    },
    {
        "name": "Check ZPOPMIN pops the lowest member",
        "command": "ZPOPMIN",
        "args": [b"k"],
        "returns": [b"a", b"1"],
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a", b"2", b"b"], "returns": 2}],
    },
    {
        "name": "Check ZPOPMAX with a count pops highest first",
        "command": "ZPOPMAX",
        "args": [b"k", b"2"],
        "returns": [b"c", b"3", b"b", b"2"],
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a", b"2", b"b", b"3", b"c"], "returns": 3}],
    },
    {
        "name": "Check ZPOPMIN on a missing key",
        "command": "ZPOPMIN",
        "args": [b"nokey"],
        "returns": [],
    },
    {
        "name": "Check ZPOPMIN empties and deletes the key",
        "command": "ZPOPMIN",
        "args": [b"k", b"5"],
        "returns": [b"a", b"1"],
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a"], "returns": 1}],
        "expects": lambda cs: cs.EXISTS(b"k") == b":0\r\n",
    },
    {
        "name": "Check ZREMRANGEBYRANK removes a rank window",
        "command": "ZREMRANGEBYRANK",
        "args": [b"k", b"0", b"1"],
        "returns": 2,
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a", b"2", b"b", b"3", b"c"], "returns": 3}],
        "expects": lambda cs: cs.ZRANGE(b"k", b"0", b"-1") == b"*1\r\n$1\r\nc\r\n",
    },
    {
        "name": "Check ZREMRANGEBYSCORE removes a score window",
        "command": "ZREMRANGEBYSCORE",
        "args": [b"k", b"2", b"+inf"],
        "returns": 2,
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a", b"2", b"b", b"3", b"c"], "returns": 3}],
        "expects": lambda cs: cs.ZCARD(b"k") == b":1\r\n",
    },
    # lex family (equal scores)
    {
        "name": "Check ZRANGEBYLEX ordering",
        "command": "ZRANGEBYLEX",
        "args": [b"k", b"-", b"+"],
        "returns": [b"a", b"b", b"c", b"d"],
        "depends": [{"command": "ZADD", "args": [b"k", b"0", b"d", b"0", b"a", b"0", b"c", b"0", b"b"], "returns": 4}],
    },
    {
        "name": "Check ZRANGEBYLEX window with exclusive max",
        "command": "ZRANGEBYLEX",
        "args": [b"k", b"[b", b"(d"],
        "returns": [b"b", b"c"],
        "depends": [{"command": "ZADD", "args": [b"k", b"0", b"a", b"0", b"b", b"0", b"c", b"0", b"d"], "returns": 4}],
    },
    {
        "name": "Check ZREVRANGEBYLEX returns descending",
        "command": "ZREVRANGEBYLEX",
        "args": [b"k", b"+", b"-"],
        "returns": [b"d", b"c", b"b", b"a"],
        "depends": [{"command": "ZADD", "args": [b"k", b"0", b"a", b"0", b"b", b"0", b"c", b"0", b"d"], "returns": 4}],
    },
    {
        "name": "Check ZLEXCOUNT counts the window",
        "command": "ZLEXCOUNT",
        "args": [b"k", b"[b", b"+"],
        "returns": 3,
        "depends": [{"command": "ZADD", "args": [b"k", b"0", b"a", b"0", b"b", b"0", b"c", b"0", b"d"], "returns": 4}],
    },
    {
        "name": "Check ZREMRANGEBYLEX removes the window",
        "command": "ZREMRANGEBYLEX",
        "args": [b"k", b"[a", b"[b"],
        "returns": 2,
        "depends": [{"command": "ZADD", "args": [b"k", b"0", b"a", b"0", b"b", b"0", b"c", b"0", b"d"], "returns": 4}],
        "expects": lambda cs: cs.ZRANGEBYLEX(b"k", b"-", b"+") == b"*2\r\n$1\r\nc\r\n$1\r\nd\r\n",
    },
    # store commands
    {
        "name": "Check ZUNIONSTORE sums scores of shared members",
        "command": "ZUNIONSTORE",
        "args": [b"dst", b"2", b"a", b"b"],
        "returns": 3,
        "depends": [
            {"command": "ZADD", "args": [b"a", b"1", b"x", b"2", b"y"], "returns": 2},
            {"command": "ZADD", "args": [b"b", b"3", b"y", b"4", b"z"], "returns": 2},
        ],
        "expects": lambda cs: cs.ZRANGE(b"dst", b"0", b"-1", b"WITHSCORES")
        == b"*6\r\n$1\r\nx\r\n$1\r\n1\r\n$1\r\nz\r\n$1\r\n4\r\n$1\r\ny\r\n$1\r\n5\r\n",
    },
    {
        "name": "Check ZINTERSTORE keeps only shared members",
        "command": "ZINTERSTORE",
        "args": [b"dst", b"2", b"a", b"b"],
        "returns": 1,
        "depends": [
            {"command": "ZADD", "args": [b"a", b"1", b"x", b"2", b"y"], "returns": 2},
            {"command": "ZADD", "args": [b"b", b"3", b"y", b"4", b"z"], "returns": 2},
        ],
        "expects": lambda cs: cs.ZSCORE(b"dst", b"y") == b"$1\r\n5\r\n",
    },
    {
        "name": "Check ZDIFFSTORE keeps the first set minus the rest",
        "command": "ZDIFFSTORE",
        "args": [b"dst", b"2", b"a", b"b"],
        "returns": 1,
        "depends": [
            {"command": "ZADD", "args": [b"a", b"1", b"x", b"2", b"y"], "returns": 2},
            {"command": "ZADD", "args": [b"b", b"3", b"y", b"4", b"z"], "returns": 2},
        ],
        "expects": lambda cs: cs.ZSCORE(b"dst", b"x") == b"$1\r\n1\r\n",
    },
    {
        "name": "Check ZUNIONSTORE with WEIGHTS and AGGREGATE MIN",
        "command": "ZUNIONSTORE",
        "args": [b"dst", b"2", b"a", b"b", b"WEIGHTS", b"2", b"3", b"AGGREGATE", b"MIN"],
        "returns": 3,
        "depends": [
            {"command": "ZADD", "args": [b"a", b"1", b"x", b"2", b"y"], "returns": 2},
            {"command": "ZADD", "args": [b"b", b"3", b"y", b"4", b"z"], "returns": 2},
        ],
        "expects": lambda cs: cs.ZSCORE(b"dst", b"y") == b"$1\r\n4\r\n",
    },
    {
        "name": "Check ZUNIONSTORE of an empty result deletes the destination",
        "command": "ZUNIONSTORE",
        "args": [b"dst", b"1", b"missing"],
        "returns": 0,
        "depends": [{"command": "SET", "args": [b"dst", b"old"], "returns": Response.OK}],
        "expects": lambda cs: cs.EXISTS(b"dst") == b":0\r\n",
    },
    {
        "name": "Check ZUNION reads with WITHSCORES",
        "command": "ZUNION",
        "args": [b"1", b"a", b"WITHSCORES"],
        "returns": [b"x", b"1", b"y", b"2"],
        "depends": [{"command": "ZADD", "args": [b"a", b"1", b"x", b"2", b"y"], "returns": 2}],
    },
    {
        "name": "Check ZRANDMEMBER picks an existing member",
        "command": "ZRANDMEMBER",
        "args": [b"k"],
        "returns": lambda rv, cs: rv in (b"a", b"b", b"c"),
        "depends": [{"command": "ZADD", "args": [b"k", b"1", b"a", b"2", b"b", b"3", b"c"], "returns": 3}],
    },
]
